In [253]:
import numpy as np
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [269]:
#params
num_dcs=3
num_customers=2
num_commodities=3
dcs_per_customer=1
orders_per_day=3
demand_mean=100
demand_var= 20

base_dc_assignment = np.zeros(num_dcs)
base_dc_assignment[0:dcs_per_customer] = 1

dcs_per_customer_array = np.array([np.random.permutation(base_dc_assignment) for c in range(num_customers)])

In [317]:
_dcs_per_customer_array = np.array([[1,1,1,0],[1,0,0,1]])
_chosen_customer=_dcs_per_customer_array[1,:]
np.random.choice(np.argwhere(_chosen_customer>0).reshape(-1))#TODO aqui quede choose one of the indexes where customer is > 0
#dcs_per_customer_array[0,dcs_per_customer_array[0]>0]

0

In [127]:
# Modelling demand
means = np.random.poisson(demand_mean,size=num_customers)
means

#Very simple demand generator: customers have one mean and all products are sampled from it.
#Random demand vector generator. in the future may change covariance matrix to reflect product 
np.floor(np.random.multivariate_normal(means,np.eye(num_customers)*demand_var,size=num_commodities)) # Resulting size: (commodities,customers)

array([[ 97., 121.],
       [ 92., 124.],
       [113., 136.]])

In [229]:
np.random.multivariate_normal([200,100,50],np.eye(3)*demand_var,size=(10,5))

array([[[200.00402398,  96.81730181,  58.38262628],
        [196.83886843, 100.41102918,  51.20075883],
        [199.49630971,  98.02718883,  47.26719603],
        [199.47382129, 100.88185469,  53.53342632],
        [208.12445419, 109.92275442,  51.07862697]],

       [[204.15517276,  98.23782582,  48.54499151],
        [203.20970959, 102.02309611,  44.79162657],
        [193.14013072, 103.6889355 ,  56.4321421 ],
        [195.62351336, 101.394757  ,  54.06117466],
        [198.24800218,  97.73676869,  51.2245593 ]],

       [[196.39458263,  97.64349937,  50.78856558],
        [202.83336028,  99.88172952,  52.9464048 ],
        [203.51317969, 100.29338851,  55.09101657],
        [203.83407327,  99.52668678,  54.58792579],
        [202.83378185,  89.89156243,  57.58215397]],

       [[199.04487713, 105.39306329,  55.07365675],
        [205.34228049,  98.63024875,  44.27647078],
        [196.51044038, 103.01688996,  54.7772901 ],
        [209.67044876, 100.52245345,  52.52831953],
      

In [267]:
#order generation
chosen_customers = np.random.choice(np.arange(num_customers),size=orders_per_day,replace=True)

# choose the customers means.
means
chosen_customers
order_means = means[chosen_customers]
np.random.multivariate_normal(order_means,np.eye(orders_per_day)*demand_var,size=num_commodities) #shape (num_commodities,num_orders) # You could compute this beforehand for performance, but let's do it on demand for now.

array([103, 122])

array([0, 1, 1])

array([[111.37752438, 122.7648287 , 127.51165566],
       [108.48000025, 129.9224677 , 118.53178941],
       [ 98.27429983, 121.65975885, 124.86374497]])

In [228]:
np.random.dirichlet([5.]*num_dcs,size=num_commodities)#shape (num_commodities, num_dcs)

array([[0.37870815, 0.28227401, 0.33901785],
       [0.37936902, 0.50790021, 0.11273077],
       [0.29415686, 0.21947477, 0.48636837]])

In [318]:
for ci in np.array([0,1,1]):
    print(ci)

0
1
1


In [334]:
a = {}

a.setdefault("1",[0]*num_commodities)[1]=5
a.setdefault("1",[0]*num_commodities)[0]=3
a

{'1': [3, 5, 0]}

In [353]:
ndcs=4
total_demand= np.array([15,25])
even = total_demand//ndcs
total_demand
np.array([even]*ndcs)#.reshape(-1,1)
np.array([even]*ndcs).reshape(ndcs,-1)

array([15, 25])

array([[3, 6],
       [3, 6],
       [3, 6],
       [3, 6]])

array([[3, 6],
       [3, 6],
       [3, 6],
       [3, 6]])

In [358]:
ndcs=4
total_demand= 25
even = total_demand//ndcs
total_demand
np.array([even]*ndcs).shape#.reshape(-1,1)
np.array([even]*ndcs).reshape(ndcs,-1).shape
np.array([even]*ndcs).reshape(-1,1).shape

25

(4,)

(4, 1)

(4, 1)